version: '3'
services:
  flaskapp:
    build: 
      context: ./ui
      dockerfile: Dockerfile-skills-app
    ports:
      - "5090:5090"
    networks:
      - web_nw
  # NOTE: uncomment this block if you want to run a local
  #       version of Elasticsearch
  #elasticsearch:
  #  image: "docker.elastic.co/elasticsearch/elasticsearch:5.4.3"
  #  environment:
  #    - "discovery.type=single-node"
  #    - "xpack.security.enabled=false"
  #    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #  ports:
  #    - "9200:9200"
  #  networks:
  #    - web_nw
networks:
  web_nw:
    driver: bridge
